version: '3.7'

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  kotov-ab-my-netology-hw:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

services:

  prometheus:
    container_name: kotov-ab-netology-prometheus
    image: prom/prometheus:v2.36.2
    depends_on:
      - pushgateway
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks: 
      kotov-ab-my-netology-hw:
        ipv4_address: 10.5.0.10
    restart: unless-stopped

  grafana:
    container_name: kotov-ab-netology-grafana
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 80:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/custom.ini:/etc/grafana/grafana.ini
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
    networks:
      kotov-ab-my-netology-hw:
        ipv4_address: 10.5.0.12
    restart: unless-stopped

  pushgateway:
    container_name: kotov-ab-netology-pushgateway
    image: prom/pushgateway
    ports:
      - "9091:9091"
    networks:
      kotov-ab-my-netology-hw:
        ipv4_address: 10.5.0.11
    restart: unless-stopped